# GitHub Actions workflow for Continuos Integration tests
name: MySQL-PHP

on: [push, pull_request]

env:
  MYSQL_DATABASE: p3_db_test
  MYSQL_ROOT_HOST: 'localhost'
  MYSQL_ROOT_PASSWORD: secret123
  MYSQL_HOST: 'localhost'
  MYSQL_PORT: 3306
  MYSQL_USER: p3_db_user
  MYSQL_PASSWORD: secret123

jobs:

  build_and_test:      
    strategy:
      fail-fast: false
      matrix:
        operating-systems: [ubuntu-latest]
        php-versions: ['7.1']
        composer-deps: ['latest']

    runs-on: ${{ matrix.operating-systems }}

    services:
      mysql:
        image: mysql:5.6
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_ROOT_HOST }}
          #MYSQL_ROOT_HOST: ${{ env.MYSQL_ROOT_HOST }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_HOST }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_PORT: ${{ env.MYSQL_PORT }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 3306/tcp
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Test MySQL connection to "localhost"
        id: mysql-cli-test
        run: mysql --host=localhost --protocol=TCP --port=${{ job.services.mysql.ports[3306] }} --user=${{ env.MYSQL_USER }} --password=${{ env.MYSQL_PASSWORD }} -e "SHOW DATABASES"

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: pdo, pdo_mysql

      - name: Test MySQLi connection
        id: php-mysqli-test
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        shell: php {0}
        run: |
          <?php
          $dbhost = getenv('MYSQL_HOST');
          $dbhost = $dbhost === '%' ? '0.0.0.0' : $dbhost;
          $dbport = getenv('MYSQL_PORT');
          $dbuser = getenv('MYSQL_USER');
          $dbpass = getenv('MYSQL_PASSWORD');
          echo "MYSQL PARAMS = host=$dbhost; port=$dbport; user=$dbuser; pass=$dbhost;\n\n";
          $mysqli = new mysqli($dbhost, $dbuser, $dbpass, "", $dbport);
          $mysqli->set_charset('utf8');          
          echo 'MySQLi HOST INFO = ' . $mysqli->host_info . "\n\n";
          $result = $mysqli->query("SHOW DATABASES");
          if ($result) {
            print_r($result->fetch_all(MYSQL_ASSOC));
          }
          ?>
          
      - name: Test PDO MySQL connection
        id: php-pdo-mysql-test
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        shell: php {0}
        run: |
          <?php
          $dbhost = getenv('MYSQL_HOST');
          $dbhost = $dbhost === '%' ? '0.0.0.0' : $dbhost;
          $dbport = getenv('MYSQL_PORT');
          $dbuser = getenv('MYSQL_USER');
          $dbpass = getenv('MYSQL_PASSWORD');
          echo "MYSQL PARAMS = host=$dbhost; port=$dbport; user=$dbuser; pass=$dbhost;\n\n";
          $pdo = new PDO(
              "mysql://{$dbuser}:{$dbpass}@host={$dbhost};port={$dbport};charset=utf8"
          );
          $stmt = $pdo->query("SHOW DATABASES");
          if ($stmt) {
            print_r($stmt->fetchAll(\PDO::FETCH_ASSOC));
          }
          ?>
