# GitHub Actions workflow for Continuos Integration tests
name: MySQL-PHP

on: [push, pull_request]

env:
  COMPOSER_ARGS: '--no-interaction --no-progress --prefer-dist --optimize-autoloader'

jobs:

  build-and-test:
    env:
      MYSQL_PORT: 3306
      
    strategy:
      fail-fast: false
      matrix:
        operating-systems: [ubuntu-latest]
        php-versions: ['7.1']
        composer-deps: ['latest']

    runs-on: ${{ matrix.operating-systems }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: p3_db_test
          MYSQL_ROOT_PASSWORD: secret123
          MYSQL_HOST: '%'
          MYSQL_PORT: ${{ job.env.MYSQL_PORT }}
          MYSQL_USER: p3_db_testuser
          MYSQL_PASSWORD: secret123
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 127.0.0.1:${{ job.env.MYSQL_PORT }}:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: pdo, pdo_mysql

      - name: Test MySQL connection to "localhost"
        id: mysql-cli-test
        run: mysql --host=localhost --protocol=TCP --port=${{ job.env.MYSQL_PORT }} --user=p3_db_testuser --password=secret123 -e "SHOW DATABASES"

      - name: Test PDO MySQL
        id: php-pdo-mysql-test
        env:
          MYSQL_HOST: localhost
          MYSQL_PORT: ${{ job.env.MYSQL_PORT }}
        shell: php {0}
        run: |
          <?php
          $port = getenv('MYSQL_PORT');
          echo "MYSQL_PORT = $port\n\n";
          $pdo = new PDO("mysql:host=localhost;port={$port};dbname=p3_db_test;charset=utf8", 'p3_db_testuser', 'secret123');
          $stmt = $pdo->query("SHOW DATABASES");
          if ($stmt) {
            print_r($stmt->fetchAll(\PDO::FETCH_ASSOC));
          }
          ?>
