# GitHub Actions workflow for Continuos Integration tests
name: MySQL-PHP

on: [push, pull_request]

env:
  COMPOSER_ARGS: '--no-interaction --no-progress --prefer-dist --optimize-autoloader'

jobs:

  build_and_test:      
    strategy:
      fail-fast: false
      matrix:
        operating-systems: [ubuntu-latest]
        php-versions: ['7.1']
        composer-deps: ['latest']

    runs-on: ${{ matrix.operating-systems }}

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: p3_db_test
          #MYSQL_ROOT_HOST: '%'
          MYSQL_ROOT_PASSWORD: secret123
          MYSQL_HOST: '172.*.*.*'
          MYSQL_PORT: 3306
          MYSQL_USER: p3_db_testuser
          MYSQL_PASSWORD: secret123
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        ports:
          - 127.0.0.1:3306:3306
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: pdo, pdo_mysql

      - name: Test MySQL connection to "localhost"
        id: mysql-cli-test
        run: mysql --host=localhost --protocol=TCP --port=3306 --user=p3_db_testuser --password=secret123 -e "SHOW DATABASES"

      - name: Test PDO MySQL
        id: php-pdo-mysql-test
        shell: php {0}
        run: |
          <?php
          $pdo = new PDO(
              "mysql:host=localhost;port=3306;dbname=mysql;charset=utf8", 
              'p3_db_testuser', 
              'secret123'
          );
          $stmt = $pdo->query("SHOW DATABASES");
          if ($stmt) {
            print_r($stmt->fetchAll(\PDO::FETCH_ASSOC));
          }
          ?>
